# Generated by Django 4.2.4 on 2023-09-01 14:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='../static/img/placeholder_avatar.png', null=True, upload_to=users.models.upload_to_profile),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('client', 'client user'), ('admin', 'admin user'), ('manufacturer', 'manufacturer user')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
