# Generated by Django 4.2.4 on 2023-09-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
        ('users', '0002_userprofile_profile_image_userprofile_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bought_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourite_products',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='sklep.product'),
        ),
    ]
