# Generated by Django 4.2.4 on 2023-09-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_favourite_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=127)),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(choices=[(7, 'weekly'), (14, 'bi-weekly'), (31, 'monthly')], default=7)),
            ],
        ),
    ]
