# Generated by Django 4.2.4 on 2023-10-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscriber_slug_alter_subscriber_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
