# Generated by Django 4.2.4 on 2023-10-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_subscriber_frequency_subscriber_name_subscriber_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='conf_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
