# Generated by Django 4.2.4 on 2023-09-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effecttype',
            name='slug',
            field=models.SlugField(blank=True, default='temp', unique=True),
        ),
    ]
