# Generated by Django 4.2.4 on 2023-09-05 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0005_rename_products_count_manufacturer_product_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('days_minimum', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='shipping',
            new_name='shipping_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=10.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.ManyToManyField(null=True, to='sklep.shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ManyToManyField(null=True, to='sklep.shipping'),
        ),
    ]
