# Generated by Django 4.2.4 on 2023-09-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0006_shipping_rename_shipping_cart_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='slug',
            field=models.SlugField(default='temp', unique=True),
        ),
    ]
