# Generated by Django 4.2.4 on 2023-09-05 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0007_shipping_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='slug',
            field=models.SlugField(blank=True, default='temp', unique=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.shipping'),
        ),
    ]
