# Generated by Django 4.2.4 on 2023-09-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0008_remove_cart_shipping_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping',
        ),
    ]
