# Generated by Django 4.2.4 on 2023-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0009_remove_product_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='power_type',
            field=models.CharField(blank=True, choices=[('9v', '9V Powered'), ('12v', '12V Powered'), ('inline ', 'Inline Power')], max_length=50),
        ),
    ]
