# Generated by Django 4.2.4 on 2023-09-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0011_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
    ]
