# Generated by Django 4.2.4 on 2023-09-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0012_remove_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bypass',
            field=models.BooleanField(blank=True, default=True, help_text="Only required if product of type 'effect'"),
        ),
        migrations.AlterField(
            model_name='product',
            name='effect_type',
            field=models.ForeignKey(blank=True, help_text="Only required if product of type 'effect'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sklep.effecttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_type',
            field=models.CharField(blank=True, choices=[('9v', '9V Powered'), ('12v', '12V Powered'), ('inline ', 'Inline Power')], help_text="Only required if product of type 'effect'", max_length=50),
        ),
    ]
