# Generated by Django 4.2.4 on 2023-09-09 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0014_alter_effecttype_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
