# Generated by Django 4.2.4 on 2023-09-10 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0017_alter_cart_discount_alter_cart_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
