# Generated by Django 4.2.4 on 2023-09-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0018_alter_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='character',
            field=models.CharField(blank=True, help_text="eg. 'fuzzy', 'slick'", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(blank=True, choices=[('compact', 'compact'), ('full', 'full sized'), ('double', 'double')], default='compact', help_text="Only required if product of type 'effect'", max_length=25),
        ),
    ]
