# Generated by Django 4.2.4 on 2023-09-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0024_remove_cart_discount_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date_valid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
