# Generated by Django 4.2.4 on 2023-09-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0026_remove_order_items_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sum_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
