# Generated by Django 4.2.4 on 2023-09-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0027_order_sum_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
