# Generated by Django 4.2.4 on 2023-10-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0029_alter_product_bypass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='power_type',
            field=models.CharField(blank=True, choices=[('9v', '9V Powered'), ('12v', '12V Powered'), ('inline ', 'Inline Power')], help_text="Only required if product of type 'effect'", max_length=50, null=True),
        ),
    ]
